  version: '3'
    
  services:
    mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: django
        MONGO_INITDB_ROOT_PASSWORD: django
      container_name: annserver-db

    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: django
        ME_CONFIG_MONGODB_ADMINPASSWORD: django
      container_name: annserver-db-express

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:81
      volumes:
        - .:/annserver
      environment:
        - USE_DOCKER=yes
      container_name: annserver-web
      ports:
        - "81:81"
      depends_on:
        - mongo
      entrypoint: /annserver/docker-entrypoint.sh